config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :publishers
  resources :origins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/models/power.rb
class Power < ApplicationRecord
    has_and_belongs_to_many :characters
  end
  

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :api_detail_url, :count_of_issue_appearances, :deck, :description, :string, :gender, :image, :origin, :publisher, :real_name, :power)
    end
end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController
  before_action :set_origin, only: %i[ show edit update destroy ]

  # GET /origins or /origins.json
  def index
    @origins = Origin.all
  end

  # GET /origins/1 or /origins/1.json
  def show
  end

  # GET /origins/new
  def new
    @origin = Origin.new
  end

  # GET /origins/1/edit
  def edit
  end

  # POST /origins or /origins.json
  def create
    @origin = Origin.new(origin_params)

    respond_to do |format|
      if @origin.save
        format.html { redirect_to origin_url(@origin), notice: "Origin was successfully created." }
        format.json { render :show, status: :created, location: @origin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /origins/1 or /origins/1.json
  def update
    respond_to do |format|
      if @origin.update(origin_params)
        format.html { redirect_to origin_url(@origin), notice: "Origin was successfully updated." }
        format.json { render :show, status: :ok, location: @origin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /origins/1 or /origins/1.json
  def destroy
    @origin.destroy

    respond_to do |format|
      format.html { redirect_to origins_url, notice: "Origin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_origin
      @origin = Origin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def origin_params
      params.require(:origin).permit(:origin)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
    def index
      @powers = Power.all
      @origins = Origin.all
    end

    def show
      @power = Power.find(params[:id])
      @characters = @power.characters
      @origins = Origin.all
    end
  end
  

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: %i[ show edit update destroy ]

  # GET /publishers or /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1 or /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers or /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully created." }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1 or /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully updated." }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1 or /publishers/1.json
  def destroy
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url, notice: "Publisher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publisher_params
      params.require(:publisher).permit(:name, :api_detail_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/characters/_character.html.erb
<div id="<%= dom_id character %>">
  <p>
    <strong>Name:</strong>
    <%= character.name %>
  </p>

  <p>
    <strong>Api detail url:</strong>
    <%= character.api_detail_url %>
  </p>

  <p>
    <strong>Count of issue appearances:</strong>
    <%= character.count_of_issue_appearances %>
  </p>

  <p>
    <strong>Deck:</strong>
    <%= character.deck %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= character.description %>
  </p>

  <p>
    <strong>String:</strong>
    <%= character.string %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= character.gender %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= character.image %>
  </p>

  <p>
    <strong>Origin:</strong>
    <%= character.origin %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= character.publisher %>
  </p>

  <p>
    <strong>Real name:</strong>
    <%= character.real_name %>
  </p>

  <p>
    <strong>Power:</strong>
    <%= character.power %>
  </p>

</div>

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :api_detail_url, style: "display: block" %>
    <%= form.text_field :api_detail_url %>
  </div>

  <div>
    <%= form.label :count_of_issue_appearances, style: "display: block" %>
    <%= form.number_field :count_of_issue_appearances %>
  </div>

  <div>
    <%= form.label :deck, style: "display: block" %>
    <%= form.text_field :deck %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :string, style: "display: block" %>
    <%= form.text_field :string %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :origin, style: "display: block" %>
    <%= form.text_field :origin %>
  </div>

  <div>
    <%= form.label :publisher, style: "display: block" %>
    <%= form.text_field :publisher %>
  </div>

  <div>
    <%= form.label :real_name, style: "display: block" %>
    <%= form.text_field :real_name %>
  </div>

  <div>
    <%= form.label :power, style: "display: block" %>
    <%= form.text_field :power %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/by_publisher.html.erb
<h1>Characters by Publisher: <%= @publisher.name %></h1>

<% @characters.each do |character| %>
  <!-- Muestra los detalles del personaje -->
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Show this character", @character %> |
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Characters</h1>

<div id="characters">
  <% @characters.each do |character| %>
    <%= render character %>
    <p>
      <%= link_to "Show this character", character %>
    </p>
  <% end %>
</div>

<%= link_to "New character", new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @character %>

<div>
  <%= link_to "Edit this character", edit_character_path(@character) %> |
  <%= link_to "Back to characters", characters_path %>

  <%= button_to "Destroy this character", @character, method: :delete %>
</div>

app/views/layouts/_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marvel Character List</title>
    <!-- Importa los archivos CSS de Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  </head>
  <body>
    <!-- Menú de navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Characters</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/characters">Characters</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/publishers">Publishers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/origins">Origins</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Contenido de la página -->
    <div class="container">
      <%= yield %>
    </div>

    <!-- Importa los archivos JS de Bootstrap al final del documento -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicCharacters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marvel Character List</title>
    <!-- Importa los archivos CSS de Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  </head>
  <body>
    <!-- Menú de navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Tu Aplicación</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/characters">Characters</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/publishers">Publishers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/origins">Origins</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Contenido de la página -->
    <div class="container">
      <%= yield %>
    </div>

    <!-- Importa los archivos JS de Bootstrap al final del documento -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/origins/_form.html.erb
<%= form_with(model: origin) do |form| %>
  <% if origin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(origin.errors.count, "error") %> prohibited this origin from being saved:</h2>

      <ul>
        <% origin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :origin, style: "display: block" %>
    <%= form.text_field :origin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/origins/_origin.html.erb
<div id="<%= dom_id origin %>">
  <p>
    <strong>Origin:</strong>
    <%= origin.origin %>
  </p>

</div>

app/views/origins/characters_by_origin.html.erb
<%= render '/layouts/layout' %>
<p style="color: green"><%= notice %></p>

<style>
  .thumbnail-image {
    max-width: 100px;
    max-height: 60px;
  }
</style>
<h1>Characters by Origin</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>                
        <th>Image</th>
        <th>Origin</th>
      </tr>
    </thead>
    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td><%= character.name %></td>
          <td><%= image_tag character.image, class: "thumbnail-image" %></td>
          <td><%= character.origin.origin %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/origins/edit.html.erb
<h1>Editing origin</h1>

<%= render "form", origin: @origin %>

<br>

<div>
  <%= link_to "Show this origin", @origin %> |
  <%= link_to "Back to origins", origins_path %>
</div>

app/views/origins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Origins</h1>

<div id="origins">
  <% @origins.each do |origin| %>
    <%= render origin %>
    <p>
      <%= link_to "Show this origin", origin %>
    </p>
  <% end %>
</div>

<%= link_to "New origin", new_origin_path %>

app/views/origins/new.html.erb
<h1>New origin</h1>

<%= render "form", origin: @origin %>

<br>

<div>
  <%= link_to "Back to origins", origins_path %>
</div>

app/views/origins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @origin %>

<div>
  <%= link_to "Edit this origin", edit_origin_path(@origin) %> |
  <%= link_to "Back to origins", origins_path %>

  <%= button_to "Destroy this origin", @origin, method: :delete %>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/powers/index.html.erb
<%= render '/layouts/layout' %>
<p style="color: green"><%= notice %></p>


<h1>Powers</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Details</th>
    </tr>
  </thead>
  <tbody>
    <% @powers.each do |power| %>
      <tr>
        <td><%= power.name %></td>
        <td><%= power.description %></td>
        <td><%= link_to 'Show', power %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/powers/show.html.erb
<!-- app/views/powers/show.html.erb -->
<%= render '/layouts/layout' %>
<p style="color: green"><%= notice %></p>

<h1><%= @power.name %></h1>

<% if @characters.any? %>
  <h2>Characters with this power:</h2>
  <ul>
    <% @characters.each do |character| %>
      <li><%= link_to character.name, character_path(character) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No characters found with this power.</p>
<% end %>

app/views/publishers/_form.html.erb
<%= form_with(model: publisher) do |form| %>
  <% if publisher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :api_detail_url, style: "display: block" %>
    <%= form.text_field :api_detail_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publishers/_publisher.html.erb
<div id="<%= dom_id publisher %>">
  <p>
    <strong>Name:</strong>
    <%= publisher.name %>
  </p>

  <p>
    <strong>Api detail url:</strong>
    <%= publisher.api_detail_url %>
  </p>

</div>

app/views/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render "form", publisher: @publisher %>

<br>

<div>
  <%= link_to "Show this publisher", @publisher %> |
  <%= link_to "Back to publishers", publishers_path %>
</div>

app/views/publishers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publishers</h1>

<div id="publishers">
  <% @publishers.each do |publisher| %>
    <%= render publisher %>
    <p>
      <%= link_to "Show this publisher", publisher %>
    </p>
  <% end %>
</div>

<%= link_to "New publisher", new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render "form", publisher: @publisher %>

<br>

<div>
  <%= link_to "Back to publishers", publishers_path %>
</div>

app/views/publishers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publisher %>

<div>
  <%= link_to "Edit this publisher", edit_publisher_path(@publisher) %> |
  <%= link_to "Back to publishers", publishers_path %>

  <%= button_to "Destroy this publisher", @publisher, method: :delete %>
</div>